servidor:
  barramento: http://localhost:4567
  barramentosoap: http://localhost:8088
#  barramento: http://172.18.129.74:7080
#  barramentosoap: http://172.18.129.74:7800

mail:
  env: dsp
  test-destination: marezende@vr.com.br
  delivery: false

logging:
  config: classpath:logback-local.xml

spring:
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update

  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/gestaosva?useSSL=false
    username: root
    password: local
#    url: jdbc:mysql://db-gestaosva-dev.vrbeneficios.io:3306/gestaosva?useSSL=false
#    username: root
#    password: Igh7ohda

  rabbitmq:
    port: 5672
    host: localhost
    username: guest
    password: guest
#    host: vr-rabbitmq-dsp.vrbeneficios.io
#    username: sva-ec-app
#    password: Ea0aemo9
